version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
